// Pre-recorded audio playback — product requirements keep this to
// static files played through HTML audio, NOT live text-to-speech.
// The files live in public/audio/ and are generated by scripts/generate_audio.py.
//
// Playback is always best-effort: a missing file or a browser autoplay
// restriction must never break a payment flow, so every failure is swallowed.

export const VOICE_PROMPT_KEYS = [
  'enter_amount',
  'scan_card',
  'enter_pin',
  'payment_success',
  'payment_failed',
] as const

export type VoicePromptKey = (typeof VOICE_PROMPT_KEYS)[number]

export const AUDIO_LANGUAGES: readonly string[] = ['en', 'hi', 'ta', 'mr']

const BASE = (typeof import.meta !== 'undefined' && import.meta.env?.BASE_URL) || '/'

let currentAudio: HTMLAudioElement | null = null

function stopCurrent() {
  if (currentAudio) {
    currentAudio.pause()
    currentAudio.onended = null
    currentAudio = null
  }
}

function play(url: string): HTMLAudioElement | null {
  if (typeof Audio === 'undefined') return null // non-browser environment
  stopCurrent()
  const audio = new Audio(url)
  currentAudio = audio
  const attempt = audio.play()
  if (attempt && typeof attempt.catch === 'function') {
    attempt.catch(() => {}) // autoplay blocked before first user gesture — fine
  }
  return audio
}

export function voicePromptUrl(language: string, key: string): string {
  const lang = AUDIO_LANGUAGES.includes(language) ? language : 'en'
  return `${BASE}audio/${lang}/${key}.mp3`
}

/** Speak one of the five step prompts in the selected language. */
export function playVoicePrompt(language: string, key: VoicePromptKey) {
  if (!VOICE_PROMPT_KEYS.includes(key)) return
  play(voicePromptUrl(language, key))
}

/** Play only the success chime / failure buzz (used on agent screens). */
export function playResultTone(ok: boolean) {
  play(`${BASE}audio/${ok ? 'success' : 'failure'}.mp3`)
}

/**
 * Result feedback for customer-facing screens: tone first, then the spoken
 * "payment successful/failed" prompt in the selected language.
 */
export function playResult(language: string, ok: boolean) {
  const tone = play(`${BASE}audio/${ok ? 'success' : 'failure'}.mp3`)
  const speak = () => playVoicePrompt(language, ok ? 'payment_success' : 'payment_failed')
  if (tone) {
    tone.onended = speak
  } else {
    speak()
  }
}
