import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { jsPDF } from 'jspdf'
import { API_BASE_URL } from '../config/runtime.js'
import { Button, LoadingState, StatusPanel } from '../components/ui/index.js'

const displayValue = (value, fallback = '—') =>
  value === null || value === undefined || value === ''
    ? fallback
    : String(value)

function formatAmount(value) {
  const amount = Number(value)
  return Number.isFinite(amount)
    ? `₹${amount.toFixed(2)}`
    : displayValue(value)
}

function ReceiptDetails({ receipt }) {
  const fields = [
    ['Transaction ID', receipt.txn_id],
    ['Amount', formatAmount(receipt.amount)],
    ['Status', receipt.status],
    ['Customer ID', receipt.customer_id],
    ['Merchant / counterparty ID', receipt.counterparty_id],
    ['Timestamp', receipt.timestamp],
  ]

  if (receipt.failure_reason) {
    fields.push(['Failure reason', receipt.failure_reason])
  }

  return (
    <dl className="receipt-details">
      {fields.map(([label, value]) => (
        <div key={label}>
          <dt>{label}</dt>
          <dd>{displayValue(value)}</dd>
        </div>
      ))}
    </dl>
  )
}

export default function Receipt() {
  const { txnId } = useParams()

  const [receipt, setReceipt] = useState(null)
  const [error, setError] = useState('')

  // ─────────────────────────────────────────────
  // LOAD RECEIPT
  // ─────────────────────────────────────────────
  useEffect(() => {
    if (!txnId) {
      setError('Transaction ID is missing.')
      return
    }

    let active = true

    fetch(
      `${API_BASE_URL}/transactions/${encodeURIComponent(txnId)}/receipt`
    )
      .then(async (response) => {
        const data = await response.json()

        if (!response.ok) {
          throw new Error(
            data?.detail ||
            data?.error ||
            'Could not load this receipt.'
          )
        }

        return data
      })
      .then((data) => {
        if (active) {
          setReceipt(data)
        }
      })
      .catch((requestError) => {
        if (active) {
          setError(
            requestError.message ||
            'Could not load this receipt.'
          )
        }
      })

    return () => {
      active = false
    }
  }, [txnId])

  // ─────────────────────────────────────────────
  // DOWNLOAD PDF
  // ─────────────────────────────────────────────
  function downloadPdf() {
    if (!receipt) return

    const pdf = new jsPDF({
      unit: 'mm',
      format: 'a4',
    })

    const margin = 20

    // ───────────────────────────────────────────
    // GREEN HEADER
    // ───────────────────────────────────────────
    pdf.setFillColor(46, 88, 71)
    pdf.rect(0, 0, 210, 38, 'F')

    pdf.setTextColor(255, 255, 255)

    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(22)
    pdf.text('Batwa', margin, 17)

    pdf.setFontSize(11)
    pdf.text('Payment Receipt', margin, 27)

    // ───────────────────────────────────────────
    // TRANSACTION DETAILS
    // ───────────────────────────────────────────

    // IMPORTANT:
    // Start below the green header
    let y = 50

    const labelX = margin
    const valueX = 82

    const labelWidth = 55
    const valueWidth = 108

    const addLine = (label, value) => {
      // Label
      pdf.setTextColor(33, 39, 35)
      pdf.setFont('helvetica', 'bold')
      pdf.setFontSize(12)

      const labelLines = pdf.splitTextToSize(
        `${label}:`,
        labelWidth
      )

      pdf.text(labelLines, labelX, y)

      // Value
      pdf.setFont('helvetica', 'normal')

      const valueLines = pdf.splitTextToSize(
        displayValue(value),
        valueWidth
      )

      pdf.text(valueLines, valueX, y)

      // Move down based on longest text
      const lineCount = Math.max(
        labelLines.length,
        valueLines.length
      )

      y += Math.max(9, lineCount * 6)
    }

    addLine(
      'Transaction ID',
      receipt.txn_id
    )

    addLine(
      'Amount',
      formatAmount(receipt.amount)
    )

    addLine(
      'Status',
      receipt.status
    )

    addLine(
      'Customer ID',
      receipt.customer_id
    )

    addLine(
      'Merchant / counterparty ID',
      receipt.counterparty_id
    )

    addLine(
      'Timestamp',
      receipt.timestamp
    )

    if (receipt.failure_reason) {
      addLine(
        'Failure reason',
        receipt.failure_reason
      )
    }

    // ───────────────────────────────────────────
    // FOOTER
    // ───────────────────────────────────────────
    pdf.setDrawColor(210, 215, 211)

    pdf.line(
      margin,
      y + 4,
      190,
      y + 4
    )

    pdf.setTextColor(91, 99, 94)
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(9)

    pdf.text(
      'Generated by Batwa',
      margin,
      y + 12
    )

    // ───────────────────────────────────────────
    // SAVE
    // ───────────────────────────────────────────
    pdf.save(
      `batwa-receipt-${displayValue(
        receipt.txn_id,
        txnId
      )}.pdf`
    )
  }

  // ─────────────────────────────────────────────
  // ERROR
  // ─────────────────────────────────────────────
  if (error) {
    return (
      <section className="receipt-page">
        <StatusPanel
          variant="error"
          title="Receipt unavailable"
        >
          <p>{error}</p>
        </StatusPanel>
      </section>
    )
  }

  // ─────────────────────────────────────────────
  // LOADING
  // ─────────────────────────────────────────────
  if (!receipt) {
    return (
      <section className="receipt-page">
        <LoadingState
          title="Loading receipt"
          message="Retrieving transaction details…"
        />
      </section>
    )
  }

  // ─────────────────────────────────────────────
  // RECEIPT
  // ─────────────────────────────────────────────
  return (
    <section className="receipt-page">
      <div className="receipt-card">

        <p className="batwa-eyebrow">
          Batwa · payment receipt
        </p>

        <h1>Transaction receipt</h1>

        <StatusPanel
          variant={
            receipt.status === 'SUCCESS'
              ? 'success'
              : 'error'
          }
          title={
            receipt.status === 'SUCCESS'
              ? 'Payment completed'
              : 'Payment not completed'
          }
        />

        <ReceiptDetails
          receipt={receipt}
        />

        <div className="merchant-actions">
          <Button onClick={downloadPdf}>
            Download PDF
          </Button>
        </div>

      </div>
    </section>
  )
}